### PR TITLE
Added Email feature

### PR DESCRIPTION
**Pull request by muskankhedia**
---

**This PR solves issue #10**

**What's this PR do?**
In this PR, the email feature is implemented in Jarvis-Desktop.

[Explanatory Video](https://drive.google.com/file/d/1_kaI2JWp4PSXTtJTbJYy69aMf5tQYVed/view)

### CODE REVIEW

**Comment by harkishen** [comment]
clean code!
**please refine the UI. Present UI is plain and unacceptable**

**Review by harkishen — APPROVED** [review]

**Comment by muskankhedia** [comment]
> clean code!
> **please refine the UI. Present UI is plain and unacceptable**

Yaa sure, i will implement it in some time.

**Comment by muskankhedia** [comment]
@Harkishen-Singh Can i close this PR?

**Comment by muskankhedia** [comment]
@Harkishen-Singh closing the PR.

**Comment by harkishen** [comment]
@muskankhedia why do we want to close this? Can't we simply transfer this in the main repo and get the functionality there?

**Comment by muskankhedia** [comment]
Okay I will be doing it today.

**Pull request closed without merging**
